name: Generate Snake

on:
  schedule: # Executa automaticamente uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Guilherme-Machado-Dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit e push dos arquivos
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Atualizando animação da cobrinha"
          add: "dist/*.svg"
